spring:
  mvc:
    static-path-pattern=/static/**
  aop:
    proxy-target-class=true:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/GraduateEmploymentInfo?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      filter: stat,wall,log4j
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 2000
      pool-prepared-statements: false
      max-open-prepared-statements: -1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.gr.geias.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    use-column-label: true
logging:
  level:
    com:
      looedu:
        mapper: debug
server:
  port: 8080